version: '3.8'
services:
  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - backend
    volumes:
      - ./src/frontend:/app
    restart: always
    networks:
      - app
    container_name: frontend
    environment:
      - API_URL=http://backend:8000
  
  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src/backend:/app
    restart: always
    networks:
      - app
    container_name: backend

networks:
  app:
    driver: bridge

#####################################################

#   version: '3.8'
# services:
#   flaskapi:
#     build: ./flaskapi
#     ports:
#       - "5000:5000"
#     networks:
#       - app-network

#   streamlitapp:
#     build: ./streamlitapp
#     ports:
#       - "8501:8501"
#     networks:
#       - app-network
#     environment:
#       - API_URL=http://flaskapi:5000

# networks:
#   app-network:
#     driver: bridge
